**Import libraries**

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

**Load Dataset**

In [2]:
df = pd.read_csv("Titanic.csv")

**Basic Inspection**

In [3]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [5]:
df.shape

(891, 12)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [14]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [7]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [8]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

**Duplicates Handling**

In [37]:
duplicate_count = df.duplicated().sum()

df = df.drop_duplicates()

print("Duplicate rows removed:", duplicate_count)

Duplicate rows removed: 0

zero records were removed because there is no duplicates in the titanic dataset.

In [11]:
df.shape

(891, 12)

**Mean/Median Imputation**

In [17]:
print(df['PassengerId'].mean())

446.0

In [19]:
print(df['PassengerId'].median())

446.0

In [21]:
print(df['Survived'].mean())

0.3838383838383838

In [22]:
print(df['Survived'].median())

0.0

In [24]:
print(df['Pclass'].mean())

2.308641975308642

In [25]:
print(df['Pclass'].median())

3.0

In [26]:
print(df['Age'].mean())

29.69911764705882

In [28]:
print(df['Age'].median())

28.0

In [29]:
print(df['SibSp'].mean())

0.5230078563411896

In [30]:
print(df['SibSp'].median())

0.0

In [31]:
print(df['Parch'].mean())

0.38159371492704824

In [32]:
print(df['Parch'].median())

0.0

In [33]:
print(df['Fare'].mean())

32.204207968574636

In [34]:
print(df['Fare'].median())

14.4542

**Mode Imputation**

In [36]:
print(df['Sex'].mode())

0    male
Name: Sex, dtype: object

In [38]:
print(df['Ticket'].mode())

0        1601
1      347082
2    CA. 2343
Name: Ticket, dtype: object

In [39]:
print(df['Cabin'].mode())

0        B96 B98
1    C23 C25 C27
2             G6
Name: Cabin, dtype: object

In [40]:
print(df['Embarked'].mode())

0    S
Name: Embarked, dtype: object

**Standardization**

In [41]:
df['Sex'].unique()

array(['male', 'female'], dtype=object)

In [42]:
df['Sex'] = df['Sex'].replace({
    'male': 'Male',
    'female': 'Female'
})

In [43]:
df['Sex'].unique()

array(['Male', 'Female'], dtype=object)

In [44]:
df['Ticket'].unique()

array(['A/5 21171', 'PC 17599', 'STON/O2. 3101282', '113803', '373450',
       '330877', '17463', '349909', '347742', '237736', 'PP 9549',
       '113783', 'A/5. 2151', '347082', '350406', '248706', '382652',
       '244373', '345763', '2649', '239865', '248698', '330923', '113788',
       '347077', '2631', '19950', '330959', '349216', 'PC 17601',
       'PC 17569', '335677', 'C.A. 24579', 'PC 17604', '113789', '2677',
       'A./5. 2152', '345764', '2651', '7546', '11668', '349253',
       'SC/Paris 2123', '330958', 'S.C./A.4. 23567', '370371', '14311',
       '2662', '349237', '3101295', 'A/4. 39886', 'PC 17572', '2926',
       '113509', '19947', 'C.A. 31026', '2697', 'C.A. 34651', 'CA 2144',
       '2669', '113572', '36973', '347088', 'PC 17605', '2661',
       'C.A. 29395', 'S.P. 3464', '3101281', '315151', 'C.A. 33111',
       'S.O.C. 14879', '2680', '1601', '348123', '349208', '374746',
       '248738', '364516', '345767', '345779', '330932', '113059',
       'SO/C 14885', '3101278', 'W./C. 6608', 'SOTON/OQ 392086', '343275',
       '343276', '347466', 'W.E.P. 5734', 'C.A. 2315', '364500', '374910',
       'PC 17754', 'PC 17759', '231919', '244367', '349245', '349215',
       '35281', '7540', '3101276', '349207', '343120', '312991', '349249',
       '371110', '110465', '2665', '324669', '4136', '2627',
       'STON/O 2. 3101294', '370369', 'PC 17558', 'A4. 54510', '27267',
       '370372', 'C 17369', '2668', '347061', '349241',
       'SOTON/O.Q. 3101307', 'A/5. 3337', '228414', 'C.A. 29178',
       'SC/PARIS 2133', '11752', '7534', 'PC 17593', '2678', '347081',
       'STON/O2. 3101279', '365222', '231945', 'C.A. 33112', '350043',
       '230080', '244310', 'S.O.P. 1166', '113776', 'A.5. 11206',
       'A/5. 851', 'Fa 265302', 'PC 17597', '35851', 'SOTON/OQ 392090',
       '315037', 'CA. 2343', '371362', 'C.A. 33595', '347068', '315093',
       '363291', '113505', 'PC 17318', '111240', 'STON/O 2. 3101280',
       '17764', '350404', '4133', 'PC 17595', '250653', 'LINE',
       'SC/PARIS 2131', '230136', '315153', '113767', '370365', '111428',
       '364849', '349247', '234604', '28424', '350046', 'PC 17610',
       '368703', '4579', '370370', '248747', '345770', '3101264', '2628',
       'A/5 3540', '347054', '2699', '367231', '112277',
       'SOTON/O.Q. 3101311', 'F.C.C. 13528', 'A/5 21174', '250646',
       '367229', '35273', 'STON/O2. 3101283', '243847', '11813',
       'W/C 14208', 'SOTON/OQ 392089', '220367', '21440', '349234',
       '19943', 'PP 4348', 'SW/PP 751', 'A/5 21173', '236171', '347067',
       '237442', 'C.A. 29566', 'W./C. 6609', '26707', 'C.A. 31921',
       '28665', 'SCO/W 1585', '367230', 'W./C. 14263',
       'STON/O 2. 3101275', '2694', '19928', '347071', '250649', '11751',
       '244252', '362316', '113514', 'A/5. 3336', '370129', '2650',
       'PC 17585', '110152', 'PC 17755', '230433', '384461', '110413',
       '112059', '382649', 'C.A. 17248', '347083', 'PC 17582', 'PC 17760',
       '113798', '250644', 'PC 17596', '370375', '13502', '347073',
       '239853', 'C.A. 2673', '336439', '347464', '345778', 'A/5. 10482',
       '113056', '349239', '345774', '349206', '237798', '370373',
       '19877', '11967', 'SC/Paris 2163', '349236', '349233', 'PC 17612',
       '2693', '113781', '19988', '9234', '367226', '226593', 'A/5 2466',
       '17421', 'PC 17758', 'P/PP 3381', 'PC 17485', '11767', 'PC 17608',
       '250651', '349243', 'F.C.C. 13529', '347470', '29011', '36928',
       '16966', 'A/5 21172', '349219', '234818', '345364', '28551',
       '111361', '113043', 'PC 17611', '349225', '7598', '113784',
       '248740', '244361', '229236', '248733', '31418', '386525',
       'C.A. 37671', '315088', '7267', '113510', '2695', '2647', '345783',
       '237671', '330931', '330980', 'SC/PARIS 2167', '2691',
       'SOTON/O.Q. 3101310', 'C 7076', '110813', '2626', '14313',
       'PC 17477', '11765', '3101267', '323951', 'C 7077', '113503',
       '2648', '347069', 'PC 17757', '2653', 'STON/O 2. 3101293',
       '349227', '27849', '367655', 'SC 1748', '113760', '350034',
       '3101277', '350052', '350407', '28403', '244278', '240929',
       'STON/O 2. 3101289', '341826', '4137', '315096', '28664', '347064',
       '29106', '312992', '349222', '394140', 'STON/O 2. 3101269',
       '343095', '28220', '250652', '28228', '345773', '349254',
       'A/5. 13032', '315082', '347080', 'A/4. 34244', '2003', '250655',
       '364851', 'SOTON/O.Q. 392078', '110564', '376564', 'SC/AH 3085',
       'STON/O 2. 3101274', '13507', 'C.A. 18723', '345769', '347076',
       '230434', '65306', '33638', '113794', '2666', '113786', '65303',
       '113051', '17453', 'A/5 2817', '349240', '13509', '17464',
       'F.C.C. 13531', '371060', '19952', '364506', '111320', '234360',
       'A/S 2816', 'SOTON/O.Q. 3101306', '113792', '36209', '323592',
       '315089', 'SC/AH Basle 541', '7553', '31027', '3460', '350060',
       '3101298', '239854', 'A/5 3594', '4134', '11771', 'A.5. 18509',
       '65304', 'SOTON/OQ 3101317', '113787', 'PC 17609', 'A/4 45380',
       '36947', 'C.A. 6212', '350035', '315086', '364846', '330909',
       '4135', '26360', '111427', 'C 4001', '382651', 'SOTON/OQ 3101316',
       'PC 17473', 'PC 17603', '349209', '36967', 'C.A. 34260', '226875',
       '349242', '12749', '349252', '2624', '2700', '367232',
       'W./C. 14258', 'PC 17483', '3101296', '29104', '2641', '2690',
       '315084', '113050', 'PC 17761', '364498', '13568', 'WE/P 5735',
       '2908', '693', 'SC/PARIS 2146', '244358', '330979', '2620',
       '347085', '113807', '11755', '345572', '372622', '349251',
       '218629', 'SOTON/OQ 392082', 'SOTON/O.Q. 392087', 'A/4 48871',
       '349205', '2686', '350417', 'S.W./PP 752', '11769', 'PC 17474',
       '14312', 'A/4. 20589', '358585', '243880', '2689',
       'STON/O 2. 3101286', '237789', '13049', '3411', '237565', '13567',
       '14973', 'A./5. 3235', 'STON/O 2. 3101273', 'A/5 3902', '364848',
       'SC/AH 29037', '248727', '2664', '349214', '113796', '364511',
       '111426', '349910', '349246', '113804', 'SOTON/O.Q. 3101305',
       '370377', '364512', '220845', '31028', '2659', '11753', '350029',
       '54636', '36963', '219533', '349224', '334912', '27042', '347743',
       '13214', '112052', '237668', 'STON/O 2. 3101292', '350050',
       '349231', '13213', 'S.O./P.P. 751', 'CA. 2314', '349221', '8475',
       '330919', '365226', '349223', '29751', '2623', '5727', '349210',
       'STON/O 2. 3101285', '234686', '312993', 'A/5 3536', '19996',
       '29750', 'F.C. 12750', 'C.A. 24580', '244270', '239856', '349912',
       '342826', '4138', '330935', '6563', '349228', '350036', '24160',
       '17474', '349256', '2672', '113800', '248731', '363592', '35852',
       '348121', 'PC 17475', '36864', '350025', '223596', 'PC 17476',
       'PC 17482', '113028', '7545', '250647', '348124', '34218', '36568',
       '347062', '350048', '12233', '250643', '113806', '315094', '36866',
       '236853', 'STON/O2. 3101271', '239855', '28425', '233639',
       '349201', '349218', '16988', '376566', 'STON/O 2. 3101288',
       '250648', '113773', '335097', '29103', '392096', '345780',
       '349204', '350042', '29108', '363294', 'SOTON/O2 3101272', '2663',
       '347074', '112379', '364850', '8471', '345781', '350047',
       'S.O./P.P. 3', '2674', '29105', '347078', '383121', '36865',
       '2687', '113501', 'W./C. 6607', 'SOTON/O.Q. 3101312', '374887',
       '3101265', '12460', 'PC 17600', '349203', '28213', '17465',
       '349244', '2685', '2625', '347089', '347063', '112050', '347087',
       '248723', '3474', '28206', '364499', '112058', 'STON/O2. 3101290',
       'S.C./PARIS 2079', 'C 7075', '315098', '19972', '368323', '367228',
       '2671', '347468', '2223', 'PC 17756', '315097', '392092', '11774',
       'SOTON/O2 3101287', '2683', '315090', 'C.A. 5547', '349213',
       '347060', 'PC 17592', '392091', '113055', '2629', '350026',
       '28134', '17466', '233866', '236852', 'SC/PARIS 2149', 'PC 17590',
       '345777', '349248', '695', '345765', '2667', '349212', '349217',
       '349257', '7552', 'C.A./SOTON 34068', 'SOTON/OQ 392076', '211536',
       '112053', '111369', '370376'], dtype=object)

In [45]:
df['Embarked'].unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [46]:
df['Cabin'].unique()

array([nan, 'C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6',
       'C23 C25 C27', 'B78', 'D33', 'B30', 'C52', 'B28', 'C83', 'F33',
       'F G73', 'E31', 'A5', 'D10 D12', 'D26', 'C110', 'B58 B60', 'E101',
       'F E69', 'D47', 'B86', 'F2', 'C2', 'E33', 'B19', 'A7', 'C49', 'F4',
       'A32', 'B4', 'B80', 'A31', 'D36', 'D15', 'C93', 'C78', 'D35',
       'C87', 'B77', 'E67', 'B94', 'C125', 'C99', 'C118', 'D7', 'A19',
       'B49', 'D', 'C22 C26', 'C106', 'C65', 'E36', 'C54',
       'B57 B59 B63 B66', 'C7', 'E34', 'C32', 'B18', 'C124', 'C91', 'E40',
       'T', 'C128', 'D37', 'B35', 'E50', 'C82', 'B96 B98', 'E10', 'E44',
       'A34', 'C104', 'C111', 'C92', 'E38', 'D21', 'E12', 'E63', 'A14',
       'B37', 'C30', 'D20', 'B79', 'E25', 'D46', 'B73', 'C95', 'B38',
       'B39', 'B22', 'C86', 'C70', 'A16', 'C101', 'C68', 'A10', 'E68',
       'B41', 'A20', 'D19', 'D50', 'D9', 'A23', 'B50', 'A26', 'D48',
       'E58', 'C126', 'B71', 'B51 B53 B55', 'D49', 'B5', 'B20', 'F G63',
       'C62 C64', 'E24', 'C90', 'C45', 'E8', 'B101', 'D45', 'C46', 'D30',
       'E121', 'D11', 'E77', 'F38', 'B3', 'D6', 'B82 B84', 'D17', 'A36',
       'B102', 'B69', 'E49', 'C47', 'D28', 'E17', 'A24', 'C50', 'B42',
       'C148'], dtype=object)

Standardisation

The categorical columns were checked for inconsistent formatting. The Sex column was standardised to consistent title case (Male/Female). The Embarked column uses consistent categorical codes (S, C, and Q). Ticket and Cabin contain identifier values with different valid formats, so their original formats were retained. The dataset does not contain a date column, so date-to-datetime conversion was not required.

**Outlier Detection**

In [49]:
outlier_cols =df.select_dtypes(include = 'number').columns

In [52]:
for col in outlier_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    
    outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]

In [53]:
df.shape

(891, 12)

Outlier Detection

The IQR method was used to identify potential outliers in the numerical variables Age, SibSp, Parch, and Fare. PassengerId, Survived, and Pclass were excluded because they are identifiers or categorical/ordinal variables rather than continuous measurements. The detected outliers were retained because they may represent legitimate passenger characteristics, such as higher fares or larger family groups. Removing them could result in the loss of meaningful information.

**Missing Values Handling**

In [56]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [58]:
df['Age'] = df['Age'].fillna(df['Age'].median())

In [64]:
df['Cabin'] = df['Cabin'].fillna('Unknown')

Cabin: Missing values were replaced with "Unknown" because Cabin is a categorical identifier and its missing values cannot be meaningfully replaced using mean or median imputation. Keeping "Unknown" also preserves the information that the cabin was not recorded.

In [65]:
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])

In [66]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

Missing Data Handling:


Age: Missing values were replaced with the median age because Age is a numerical variable and the median is less affected by extreme values.
Cabin: Missing values were replaced with "Unknown" because Cabin is a categorical variable with many missing values, and the missingness itself may contain useful information.
Embarked: Missing values were replaced with the mode because Embarked is a categorical variable and the most frequent category is an appropriate replacement.
Other columns: Columns without missing values were left unchanged.

** Data Type Conversion**

In [68]:
df = df.convert_dtypes()

In [69]:
df.dtypes

PassengerId             Int64
Survived                Int64
Pclass                  Int64
Name           string[python]
Sex            string[python]
Age                   Float64
SibSp                   Int64
Parch                   Int64
Ticket         string[python]
Fare                  Float64
Cabin          string[python]
Embarked       string[python]
dtype: object

**Before Cleaning vs After Cleaning**

In [72]:
# ---------- BEFORE CLEANING ----------
before_rows = df.shape[0]
before_nulls = df.isnull().sum().sum()
before_duplicates = df.duplicated().sum()

# Expected logical data types
expected_dtypes = {
    'PassengerId': 'int',
    'Survived': 'int',
    'Pclass': 'int',
    'Name': 'string',
    'Sex': 'string',
    'Age': 'float',
    'SibSp': 'int',
    'Parch': 'int',
    'Ticket': 'string',
    'Fare': 'float',
    'Cabin': 'string',
    'Embarked': 'string'
}

# Check dtype accuracy before cleaning
before_dtype_accuracy = sum(
    str(df[col].dtype).lower().startswith(expected.lower())
    for col, expected in expected_dtypes.items()
) / len(expected_dtypes) * 100

# ---------- AFTER CLEANING ----------
after_rows = df.shape[0]
after_nulls = df.isnull().sum().sum()
after_duplicates = df.duplicated().sum()

# Check dtype accuracy after cleaning
after_dtype_accuracy = sum(
    str(df[col].dtype).lower().startswith(expected.lower())
    for col, expected in expected_dtypes.items()
) / len(expected_dtypes) * 100

# ---------- FINAL SUMMARY TABLE ----------
summary = pd.DataFrame({
    'Metric': [
        'Row Count',
        'Total Null Count',
        'Duplicate Count',
        'Dtype Accuracy'
    ],
    'Before Cleaning': [
        before_rows,
        before_nulls,
        before_duplicates,
        f'{before_dtype_accuracy:.2f}%'
    ],
    'After Cleaning': [
        after_rows,
        after_nulls,
        after_duplicates,
        f'{after_dtype_accuracy:.2f}%'
    ]
})

print(summary)

             Metric Before Cleaning After Cleaning
0         Row Count             891            891
1  Total Null Count               0              0
2   Duplicate Count               0              0
3    Dtype Accuracy         100.00%        100.00%